# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
      with:
          fetch-depth: 0
          persist-credentials: false
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.S3_PUBLISH_KEY }}
        aws-secret-access-key: ${{ secrets.S3_PUBLISH }}
        aws-region: us-east-1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install -g npm@7
    - run: npm config set //npm.pkg.github.com/:_authToken=${{ secrets.MOPOPAK }}
    - run: npm install -g @angular/cli@10.2.0
    - run: npm ci
    - run: npm run build
    - name: Release
      env:
        GH_TOKEN: ${{ secrets.MOPOPACKAGES }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: npx semantic-release
